### ISSUE TITLE
[Enigma] Диспоз

### ISSUE THREAD

**Issue by pavel-b-novikov** [ategro/nsudotnet#1]
Я ценю ваши тщатеьлно проставленные .Close, но черт побери, весь семестр я втирал про человеческий способ работы с подобными вещами

**Comment by ategro** [comment]
Исправил

**Comment by pavel-b-novikov** [comment]
Нет, вы не все задиспозили. 
И зачем вам SetLength?

**Comment by ategro** [comment]
Действительно не нужен. Исправил
