### ISSUE TITLE
[TicTacToe] Это замечательно

### ISSUE THREAD

**Issue by pavel-b-novikov** [ategro/nsudotnet#3]
Что вы знаете generics. Однако как описанная декомпозиция помогла бы вам реализовать GUI-фронтенд? Я сейчас вижу что это решение надо переколбашивать вдоль и поперек, чтобы открутить консольный GUI и прикрутить например WPF.

**Comment by ategro** [comment]
Исправил

**Comment by pavel-b-novikov** [comment]
Хорошо .а если я хочу напрямую обновить.. ээ.. модель (она у вас разбита на Field и FieldAlternative) - отображение при этом перерисуется?

**Comment by ategro** [comment]
Исправил. Напрямую обновить модель не получится, основные методы и поля используемые для модификации приватные, но если допустить использование FieldAlternative.Set - представление измениться.

**Comment by pavel-b-novikov** [comment]
Вопрос тут в том - получится ли у вас на основе текущего кода, не меняя его, приделать UI-фронтенд (например, WPF-ный)?

**Comment by ategro** [comment]
Нет. Я вижу эту проблему. Не знаю почему я так поступил. Видимо так было легче переделать код под замечания. Идейно должно быть наоборот. Не модель должна владеть GUI, а наоборот:( Переписывать? Мне не хватает еще 3х баллов, этого не достаточно?
